name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Login to Yandex Container Registry
        run: echo ${{ secrets.YCR_TOKEN }} | docker login --username oauth --password-stdin cr.yandex
        
      - name: Verify Docker image exists
        run: |
          if ! docker pull cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_latest; then
            echo "Docker image not found!"
            exit 1
          fi
          
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: |
          ssh-keyscan -H 89.169.135.105 >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_rsa yakovchukalex@89.169.135.105 "docker pull cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_latest && docker run -d -p 3000:3000 cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_latest"

