name: Create Fix Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_fix${{ github.run_number }} .
          docker tag cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_fix${{ github.run_number }} cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_latest

      - name: Login to Yandex Container Registry
        run: echo ${{ secrets.YCR_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

      - name: Push Docker image
        run: |
          docker push cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_fix${{ github.run_number }}
          docker push cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.event.inputs.version }}_latest

      - name: Create fix tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a ${{
          github.event.inputs.version }}_fix${{ github.run_number }} -m "Fix release ${{ github.event.inputs.version }}_fix${{ github.run_number }}"
          git push origin ${{
          github.event.inputs.version }}_fix${{ github.run_number }}

      - name: get current date
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: get commits
        run: |
          # Get the list of commits
          commits=$(git log $latest_tag..HEAD --pretty=format:'%h - %s (%an)')
          echo "COMMITS=$commits" >> $GITHUB_ENV

      - name: create gitHub issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Release ${{ github.run_number }}
          body: |
            ## Fix release ${{ github.run_number }}

            - Дата: ${{ env.DATE }}
            - Автор фикса: ${{ github.actor }}
            - Версия: ${{ github.run_number }}
            - Коммиты: ${{ env.COMMITS }}
            - Ссылка на образ: cr.yandex/crprvm771nrd4eaafbdd/app:${{ github.run_number }}
